# fly.toml app configuration file generated for cors-anywhere-lively-glitter-8903 on 2024-12-03T20:07:05+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cors-anywhere-lively-glitter-8903'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = '8081'
  CORSANYWHERE_WHITELIST = "https://deckscout.fyi,http://deckscout.fly.dev,http://localhost:5225"
